package formulario;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Persona;

public class Form extends javax.swing.JFrame {

    private Persona[] registro;
    DefaultTableModel modelo = new DefaultTableModel();

    public Form() {
        initComponents();
        this.setLocationRelativeTo(this);
        registro = new Persona[0];
        inicio();
        String[] encabezados = {"Documento", "Nombre", "Edad", "Celular", "Email"};
        modelo.setColumnIdentifiers(encabezados);
        tblDatos.setModel(modelo);
    }

    public void insertar(String documento, String nombre, int edad, String email, int celular) {
        registro = redimensionar();
        registro[registro.length - 1] = new Persona(documento, nombre, email, celular, edad);
        JOptionPane.showMessageDialog(this, "Registro exitoso", "Confirmación de registro", JOptionPane.INFORMATION_MESSAGE);
        inicio();
    }

    public void actualizar(String nombre, String email, int celular, int edad) {
        registro[tblDatos.getSelectedRow()].setNombre(nombre);
        registro[tblDatos.getSelectedRow()].setEmail(email);
        registro[tblDatos.getSelectedRow()].setCelular(celular);
        registro[tblDatos.getSelectedRow()].setEdad(edad);
        JOptionPane.showMessageDialog(this, "Se actualizó el registro exitosamente");
        inicio();
    }

    public void inicio() {
        txtDocumento.setEnabled(true);
        btnRegistrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(true);
        lblContador.setText(registro.length + "");
        limpiar();
        mostrar();
    }

    public void editar(int indice) {
        txtDocumento.setText(registro[indice].getDocumento());
        txtNombre.setText(registro[indice].getNombre());
        txtEmail.setText(registro[indice].getEmail());
        txtCelular.setText(registro[indice].getCelular() + "");
        txtEdad.setText(registro[indice].getEdad() + "");
        txtDocumento.setEnabled(false);
        txtNombre.requestFocus();
        btnActualizar.setEnabled(true);
        btnRegistrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    public void mostrar() {
        if (registro != null) {
            modelo.setRowCount(0);
            for (int i = 0; i < registro.length; i++) {
                modelo.addRow(new Object[]{registro[i].getDocumento(),
                    registro[i].getNombre(),
                    registro[i].getEdad(),
                    registro[i].getCelular(),
                    registro[i].getEmail()});
            }
        }
    }

    public void limpiar() {
        txtDocumento.setText("");
        txtNombre.setText("");
        txtEmail.setText("");
        txtEdad.setText("");
        txtCelular.setText("");
        txtDocumento.requestFocus();
    }

    public Persona[] redimensionar() {
        Persona[] aux = new Persona[registro.length + 1];

        for (int i = 0; i < registro.length; i++) {
            aux[i] = registro[i];
        }

        return aux;

    }

    public int buscar(String documento) {
        for (int i = 0; i < registro.length; i++) {
            if (documento.equals(registro[i].getDocumento())) {
                return i;
            }
        }
        return -1;
    }

    public void eliminar(int indice) {
        Persona[] aux = new Persona[registro.length - 1];

        for (int i = 0; i < registro.length; i++) {
            if (i < indice) {
                aux[i] = registro[i];
            } else if (i > indice) {
                aux[i - 1] = registro[i];
            }
        }

        registro = aux;

        JOptionPane.showMessageDialog(this, "Registro eliminado");
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblContador = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Formulario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel2.setText("Documento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        txtDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDocumentoFocusLost(evt);
            }
        });
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 122, 230, 30));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 230, 30));

        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 230, 30));

        jLabel5.setText("Celular:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 230, 30));

        btnRegistrar.setBackground(new java.awt.Color(242, 242, 242));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-añadir-16.png"))); // NOI18N
        btnRegistrar.setText("Registrarse");
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrar.setIconTextGap(10);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 230, 40));

        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 230, 30));

        lblContador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador.setText("0");
        jPanel1.add(lblContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Registrados");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 610, 80));

        btnBuscar.setBackground(new java.awt.Color(242, 242, 242));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-búsqueda-16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 140, 40));

        btnEliminar.setBackground(new java.awt.Color(242, 242, 242));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-basura-16.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 140, 40));

        btnEditar.setBackground(new java.awt.Color(242, 242, 242));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-crear-nuevo-16.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 140, 40));

        btnActualizar.setBackground(new java.awt.Color(242, 242, 242));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-actualizar-16.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtNombre.getText();
        String documento = txtDocumento.getText();
        String email = txtEmail.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        int celular = Integer.parseInt(txtCelular.getText());

        insertar(documento, nombre, edad, email, celular);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String documento = JOptionPane.showInputDialog(this, "Ingrese el documento a buscar");

        int pos = buscar(documento);
        if (pos != -1) {
            modelo.setRowCount(0);
            modelo.addRow(new Object[]{registro[pos].getDocumento(),
                registro[pos].getNombre(),
                registro[pos].getEdad(),
                registro[pos].getCelular(),
                registro[pos].getEmail()});
        } else {
            JOptionPane.showMessageDialog(this, "No se encotraron resultados para la busqueda");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblDatos.getSelectedRow() != -1) {
            int op = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar el registro?", "Eliminar registro", JOptionPane.WARNING_MESSAGE);

            if (op == JOptionPane.YES_OPTION) {
                eliminar(tblDatos.getSelectedRow());
            } else {
                JOptionPane.showMessageDialog(this, "No se ha realizado ningún cambio");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblDatos.getSelectedRow() != -1) {
            editar(tblDatos.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String nombre = txtNombre.getText();
        String email = txtEmail.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        int celular = Integer.parseInt(txtCelular.getText());

        actualizar(nombre, email, celular, edad);

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocumentoFocusLost
        if (txtDocumento.getText().isBlank()) {
            btnRegistrar.setEnabled(false);
        } else {
            btnRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_txtDocumentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContador;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
